version: '3.8'

services:
  dmp-generator:
    build:
      context: .
      dockerfile: Dockerfile
    image: clinical-dmp-generator:latest
    container_name: dmp-generator
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PORT=${PORT:-3000}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - OUTPUT_DIR=/app/output
      - TEMP_DIR=/app/temp
      - LOG_DIR=/app/logs
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./temp:/app/temp
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dmp-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dmp-network:
    driver: bridge